# Generated by Django 5.0.3 on 2024-04-21 04:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notesBody', models.TextField(blank=True)),
                ('posX', models.FloatField(default=0)),
                ('posY', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('pinned', models.BooleanField(default=False)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='canvas.canvas')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
